-- Maker Shop — PostgreSQL schema (manifest §requiredSchema contract).
--
-- This is the real database behind the full self-host stack: the shop reads it
-- (through Adminium's records API) and the auto-generated Adminium dashboard is
-- the back office. Applied automatically on first boot of the `studio-db`
-- container via /docker-entrypoint-initdb.d/01-schema.sql, then seeded by
-- db/seed.sql. The seed mirrors src/data/demo.ts row for row — the same twelve
-- live orders, the same sixteen posted ones, the same ten stock rows, the same
-- pinned Thursday — so the bench and the dashboard run the same studio.
--
-- THE EIGHT TABLES BELOW ARE THE MANIFEST'S, exactly: every table and every
-- column here appears in `requiredSchema` in manifest.json, and nothing else
-- does. That document is what an add-on reads — the Live Personalizer mounts
-- its dashboard panel on `products` and `order_lines` by name (24 D20) — so a
-- column added here and not there is a promise only half made.
--
-- THERE IS NO FINISHED-GOODS STOCK IN THIS FILE, and there is nowhere to put
-- it. Every piece is made after it is ordered, so the only inventory is
-- `materials`, and `products` carries no count of any kind — a rule
-- src/lib/orders.ts is built on, src/manifest.test.ts asserts against the
-- document, and this schema states by simply having no such column.
--
-- WHAT IS DERIVED IS NOT STORED. Where an order is in its five stages, what a
-- material has committed to the open bench, what is spare, whether a piece is
-- late, the packing of a batch sheet and its use percentage, what a line takes
-- off the shelf — all computed, in src/lib/orders.ts, src/lib/batch.ts and
-- src/lib/calendar.ts in the app and in a query on the dashboard side. The one
-- exception is `orders.total`, which IS stored, because a price is not a
-- derivation of the catalogue: it is what the customer was charged, and the
-- catalogue moves. Recomputing an old order from today's prices would quietly
-- re-invoice work that was already sold and posted.
--
-- THE PROOF GATE IS NOT IN THIS FILE, and that is deliberate. `moveLine()` in
-- src/lib/orders.ts refuses to take a piece out of *To make* until its picture
-- is approved, and it names which of the two things is missing when it refuses.
-- Saying the same thing here would take a trigger that could only pretend to,
-- and a rule enforced in two places drifts in one of them. The gate lives in
-- the engine; the engine is tested.
--
-- THE STUDIO WEEK IS NOT IN THIS FILE EITHER, for the same reason. Birch Row
-- works Tuesday to Saturday with a 17:00 cut-off, and every date the app shows
-- is counted in studio days by src/lib/calendar.ts. What is stored is what
-- happened on a day somebody could point at.
--
-- Money is numeric(12, 2) — never a float; the engines work in whole cents and
-- divide once, at the edge. Millimetres are numeric because a sheet is measured
-- to a tenth. `placed_on`, `posted_on` and a proof's `at` are `date`: an order
-- is posted ON a Tuesday, not at an instant on it. A stock movement is
-- `timestamptz`, because that came off the shelf at a moment.

DROP TABLE IF EXISTS stock_movements CASCADE;
DROP TABLE IF EXISTS proofs CASCADE;
DROP TABLE IF EXISTS order_lines CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS machines CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- The people ------------------------------------------------------------------

-- Invented private people in and around one seaside town, in the
-- first-name-and-initial form somebody actually gives a small shop. Not
-- companies: a maker's customers are people, which is why there is no account,
-- no contact hierarchy and no second address for the invoice here.
--
-- The address is where the studio POSTS THEIR PARCEL, and it is on the customer
-- rather than on the order because that is where the shop knows it from. It is
-- stored whole, as lines, because a house name, a flat number and a street are
-- not three columns in every country that Birch Row will post to.
--
-- `country` is a CODE rather than a country's name in anybody's language: a
-- carrier checks the postcode against it.
CREATE TABLE customers (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  email         text NOT NULL,
  town          text NOT NULL,
  address_lines jsonb NOT NULL,
  postcode      text NOT NULL,
  country       text NOT NULL CHECK (country ~ '^[A-Z]{2}$'),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX customers_email_idx ON customers (lower(email));

-- The catalogue ---------------------------------------------------------------

-- What Birch Row makes. `key` is what the app's option graph calls it
-- (`src/lib/catalogue.ts`) and what the eight locales translate; `name` is the
-- en-US label, so the dashboard has something readable in a column header.
--
-- The option graph itself — which materials a piece can be made from, the sizes
-- with their millimetres and their price deltas, the finishes and glazes with
-- their swatches, the quantity breaks and what each one multiplies by — is NOT
-- here. It is a graph, and flattening it into join tables would leave the
-- deltas attached to nothing. It lives in `catalogue.ts` and the dashboard does
-- not edit it.
--
-- `lead_kind` is the bench a piece sits on, and the wait comes with it: coasters
-- and keyrings 3 studio days, printed pieces 4, slate 5, glazed ceramics 10
-- (they are fired twice). One name, one number, so a future edit cannot move
-- half of a shared bench.
--
-- The two `personalize_*` columns are the piece's own limit and the maker's own
-- instructions beside the field — a property of the OBJECT rather than of the
-- shop, because eighteen characters is what fits on a keyring. They are null
-- together on a piece that takes no words at all.
CREATE TABLE products (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key               text NOT NULL UNIQUE,
  name              text NOT NULL,
  category          text NOT NULL CHECK (category IN
                      ('coasters', 'signs', 'keyrings', 'pots', 'desk', 'mugs')),
  lead_kind         text NOT NULL CHECK (lead_kind IN
                      ('engraved-wood', 'keyrings', 'printed', 'slate', 'glazed')),
  -- At quantity one, in the default material and the first size. Everything
  -- else is a delta the engine applies.
  base_price        numeric(12, 2) NOT NULL CHECK (base_price >= 0),
  personalize_limit integer CHECK (personalize_limit > 0),
  personalize_hint  text,

  CONSTRAINT products_personalize_ck
    CHECK ((personalize_limit IS NULL) = (personalize_hint IS NULL))
);

CREATE INDEX products_category_idx ON products (category);

-- The shelf, and THE ONLY INVENTORY THIS APP HAS.
--
-- Four units, all of them raw material: press `sheet`s of walnut, ply and
-- acrylic, slate `blank`s, `grams` of filament and `tub`s of glaze. There is no
-- fifth unit for finished pieces and no room for one — a piece that exists is
-- on its way to somebody, and a piece that does not exist is a line on the
-- bench rather than a number on a shelf.
--
-- A stock row has no display name: the app draws it from its key through the
-- bundle, in eight languages, and a `name` column here would be an en-US label
-- competing with them.
--
-- `sheet_width_mm` and `sheet_height_mm` are the SHEET's own size — what the
-- batcher packs pieces onto — and they are null on everything that is not
-- bought as a sheet. A slate blank is one piece; filament has no edges.
CREATE TABLE materials (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key             text NOT NULL UNIQUE,
  unit            text NOT NULL CHECK (unit IN ('sheet', 'blank', 'grams', 'tub')),
  sheet_width_mm  numeric(8, 1) CHECK (sheet_width_mm > 0),
  sheet_height_mm numeric(8, 1) CHECK (sheet_height_mm > 0),
  on_hand         integer NOT NULL CHECK (on_hand >= 0),
  reorder_at      integer NOT NULL CHECK (reorder_at >= 0),

  CONSTRAINT materials_sheet_ck CHECK
    ((unit = 'sheet') = (sheet_width_mm IS NOT NULL AND sheet_height_mm IS NOT NULL))
);

CREATE INDEX materials_unit_idx ON materials (unit);

-- What is in the unit behind the station. Two printers are ONE ROW that says
-- two, because the studio talks about "the printers" and books them as one
-- queue — and a second row would invite somebody to give one of them a name.
CREATE TABLE machines (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key   text NOT NULL UNIQUE,
  count integer NOT NULL CHECK (count > 0)
);

-- The bench -------------------------------------------------------------------

-- One order is one parcel: everything in it leaves together, which is why the
-- ship-by date comes from the SLOWEST piece in it and not from the average.
--
-- `posted_on` is null until the parcel has actually gone, and setting it is the
-- only thing that makes an order finished. There is no `stage` column: where an
-- order is comes from where its pieces are (`orderStage()` in
-- src/lib/orders.ts), because two places holding the same fact is how they come
-- to disagree.
--
-- `total` is what the customer was charged, postage included. See the header.
CREATE TABLE orders (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref         text NOT NULL UNIQUE,
  customer_id integer NOT NULL REFERENCES customers (id),
  placed_on   date NOT NULL,
  posted_on   date,
  total       numeric(12, 2) NOT NULL CHECK (total >= 0),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT orders_posted_ck CHECK (posted_on IS NULL OR posted_on >= placed_on)
);

CREATE INDEX orders_customer_idx ON orders (customer_id);
CREATE INDEX orders_placed_idx ON orders (placed_on);

-- One piece being made, and the row the whole bench is drawn from.
--
-- The material, size and finish are KEYS rather than foreign keys, and that is
-- not laziness. A size is `standard` for one piece and 95 × 95mm for another;
-- a finish is `oiled` on wood and `seafoam` on a glaze. They are vocabularies
-- that only mean anything against the product they were chosen for, and a
-- `sizes` table would have to carry the product anyway. `material_key` is the
-- MATERIAL the shopper chose (walnut, ply, slate…), which is not the same thing
-- as the stock row it comes off — a walnut coaster and a walnut bookmark take
-- different sheets — so the shelf is reached through the product's footprint
-- rather than from here.
--
-- `note` is the customer's own words, exactly as they typed them, and it is
-- what the maker cuts. Null when they wrote nothing, and a piece with nothing
-- written on it needs no picture and never sees the proof gate — which the
-- CHECK below says outright rather than leaving to whoever writes the next
-- insert.
--
-- `spoiled` is the one number the customer never sees: blanks Birch Row ruined
-- and re-cut, which take the material a second time while the price stands
-- still. That asymmetry is the whole reason it is a column rather than an
-- adjustment to `quantity`.
CREATE TABLE order_lines (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     integer NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id   integer NOT NULL REFERENCES products (id),
  material_key text NOT NULL,
  size_key     text NOT NULL,
  finish_key   text NOT NULL,
  quantity     integer NOT NULL CHECK (quantity > 0),
  note         text,
  -- The four columns of Today, in the order a piece crosses them. `BENCH_COLUMNS`
  -- in src/lib/orders.ts is the same list, and src/manifest.test.ts fails the
  -- build if the manifest and the engine ever disagree about it.
  stage        text NOT NULL CHECK (stage IN
                 ('to-make', 'making', 'finishing', 'ready-to-post')),
  proof        text NOT NULL CHECK (proof IN
                 ('not-needed', 'not-sent', 'waiting', 'approved')),
  spoiled      integer NOT NULL DEFAULT 0 CHECK (spoiled >= 0),

  CONSTRAINT order_lines_proof_ck CHECK ((proof = 'not-needed') = (note IS NULL))
);

CREATE INDEX order_lines_order_idx ON order_lines (order_id);
CREATE INDEX order_lines_stage_idx ON order_lines (stage);
CREATE INDEX order_lines_product_idx ON order_lines (product_id);

-- The picture conversation, in the order it happened: accepted, sent, a change
-- asked for, sent again, approved.
--
-- It hangs off the ORDER rather than the line because that is how it is had —
-- one email with everything in it — and because the shopper's order page shows
-- one history. The gate is per piece; the conversation is per parcel.
--
-- These are rows rather than a status column because "approved" is an event
-- with a date on it, and the round trips before it are the argument for having
-- a gate at all. A note belongs to a `change-asked` and to nothing else: the
-- other three kinds are the studio's own moves.
CREATE TABLE proofs (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  kind     text NOT NULL CHECK (kind IN ('accepted', 'sent', 'change-asked', 'approved')),
  note     text,
  at       date NOT NULL,

  CONSTRAINT proofs_note_ck CHECK (kind = 'change-asked' OR note IS NULL)
);

CREATE INDEX proofs_order_idx ON proofs (order_id, at);

-- The shelf ledger ------------------------------------------------------------

-- What actually came off the shelf, and what arrived on it. Counted in the unit
-- its material row is counted in — sheets, blanks, grams or tubs — which is why
-- `quantity` is numeric rather than an integer: a mug takes 0.15 of a tub of
-- glaze, and rounding that to a whole tub would have the studio buying glaze it
-- already has.
--
-- THIS LEDGER DOES NOT ADD UP TO `on_hand`, and is not meant to. `on_hand` is
-- what the last stocktake counted; these are the movements since. A studio that
-- derived its shelf from a movement history would be one miscounted delivery
-- away from ordering walnut it is standing next to.
--
-- A consumption belongs to a piece and a delivery does not, which the CHECK says
-- outright. Spoilage belongs to a piece too — it is the second helping the same
-- line took — and it is its own kind rather than a bigger `consumed` row,
-- because "we cut it twice" is the fact the materials screen is for.
CREATE TABLE stock_movements (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id   integer NOT NULL REFERENCES materials (id),
  order_line_id integer REFERENCES order_lines (id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind IN ('consumed', 'spoilage', 'delivery')),
  quantity      numeric(12, 2) NOT NULL CHECK (quantity > 0),
  at            timestamptz NOT NULL,

  CONSTRAINT stock_movements_line_ck
    CHECK ((kind = 'delivery') = (order_line_id IS NULL))
);

CREATE INDEX stock_movements_material_idx ON stock_movements (material_id, at DESC);
CREATE INDEX stock_movements_line_idx ON stock_movements (order_line_id);
